SOAL NOMOR 1

In [ ]:
# buat matrix X berukuran 2x3 menggunakan numpy
import numpy as np

x = np.array([[1, 2, 3], [3, 2, 1]])
print (x)

# tampilkan ukuran dari matrix X
print ("Ukuran matriks x :", x.shape)

# tampilkan seluruh elemen dari kolom pertama dari matrix X
print ("Elemen kolom pertama :", x[0,:])

# tampilkan seluruh elemen dari baris kedua dari matrix X
print ("Elemen kolom kedua :", x[1,:])

[[0 6 1]
 [0 0 6]]
Ukuran matriks x : (2, 3)
Elemen kolom pertama : [0 6 1]
Elemen kolom kedua : [0 0 6]


SOAL NOMOR 2

In [1]:
# ulangi soal nomor 1 menggunakan pytorch
import torch

x_pt = torch.tensor([[1, 2, 3], [3, 2, 1]])
print (x_pt)

# tampilkan ukuran dari matrix x_pt
print ("Ukuran matriks x :", x_pt.shape)

# tampilkan seluruh elemen dari kolom pertama dari matrix x_pt
print ("Elemen kolom pertama :", x_pt[0,:])

# tampilkan seluruh elemen dari baris kedua dari matrix x_pt
print ("Elemen kolom kedua :", x_pt[1,:])

tensor([[1, 2, 3],
        [3, 2, 1]])
Ukuran matriks x : torch.Size([2, 3])
Elemen kolom pertama : tensor([1, 2, 3])
Elemen kolom kedua : tensor([3, 2, 1])


In [2]:
# ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

x_tf = tf.Variable([[1, 2, 3], [3, 2, 1]])
print (x_tf)

# tampilkan ukuran dari matrix x_tf
tf.shape(x_tf)

# tampilkan seluruh elemen dari kolom pertama dari matrix x_pt
print ("Elemen kolom pertama :", x_tf[0,:])

# tampilkan seluruh elemen dari baris kedua dari matrix x_pt
print ("Elemen kolom kedua :", x_tf[1,:])

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 2, 1]], dtype=int32)>
Elemen kolom pertama : tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Elemen kolom kedua : tf.Tensor([3 2 1], shape=(3,), dtype=int32)
