In [1]:
import numpy as np

In [3]:
#buat vector x dengan ukuran 3x1
x = np.array([25, 1, 5])
x

array([25,  1,  5])

In [4]:
#hitung panjang vector x
len(x)

3

In [5]:
#tampilkan ukuran vector x
x.shape

(3,)

In [6]:
#tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [7]:
#akses elemen pertama dari vector x
x[0]

np.int64(25)

In [8]:
#tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [9]:
#lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([25,  1,  5])

In [10]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [12]:
#lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[25, 1, 5]])
y

array([[25,  1,  5]])

In [13]:
#tampilkan ukuran dari vector x_t
y.shape

(1, 3)

In [14]:
#lakukan soal nomor 2 menggunakan pytorch dan tensorflow
y_t = y.T
y_t

array([[25],
       [ 1],
       [ 5]])