SOAL 1

In [10]:
# buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6]])

print (A)

[[1 2 3]
 [4 5 6]]


In [11]:
b = np.array([[2], [5], [5]])

print (b)

[[2]
 [5]
 [5]]


In [13]:
# buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
import torch

A_pt = torch.tensor([[1, 2, 3], [4, 5, 6]])

print (A_pt)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [14]:
b_pt = torch.tensor([[2], [5], [5]])

print (b_pt)

tensor([[2],
        [5],
        [5]])


In [16]:
# buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
import tensorflow as tf

A_tf = tf.Variable([[1, 2, 3], [4, 5, 6]])

print (A_tf)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>


In [15]:
b_tf = tf.Variable([[2], [5], [5]])

print (b_tf)

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[2],
       [5],
       [5]], dtype=int32)>


SOAL 2

In [17]:
# tampilkan ukuran matrix A dan vector b
print ("Ukuran matrix A:", A.shape)
print ("Ukuran vector b:", b.shape)

Ukuran matrix A: (2, 3)
Ukuran vector b: (3, 1)


SOAL 3

In [19]:
# kalikan matrix A dengan vector b
np.dot(A, b)

array([[27],
       [63]])

In [20]:
# kalikan matrix A_pt dengan vector b_pt
torch.matmul(A_pt, b_pt)

tensor([[27],
        [63]])

In [21]:
# kalikan matrix A_tf dengan vector b_tf
tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[27],
       [63]], dtype=int32)>

SOAL 4

In [23]:
# buat matrix B dengan ukuran 3x3 menggunakan numpy
B = np.array([[2, 5, 5], [0, 6, 1], [0, 0, 6]])

print (B)

[[2 5 5]
 [0 6 1]
 [0 0 6]]


In [24]:
# buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
B_pt = torch.tensor([[2, 5, 5], [0, 6, 1], [0, 0, 6]])

print (B_pt)

tensor([[2, 5, 5],
        [0, 6, 1],
        [0, 0, 6]])


In [25]:
# buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
B_tf = tf.Variable([[2, 5, 5], [0, 6, 1], [0, 0, 6]])

print (B_tf)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[2, 5, 5],
       [0, 6, 1],
       [0, 0, 6]], dtype=int32)>


SOAL 5

In [26]:
# kalikan matrix A dengan matrix B
np.dot(A, B)

array([[ 2, 17, 25],
       [ 8, 50, 61]])

In [27]:
# kalikan matrix A_pt dengan matrix B_pt
torch.matmul(A_pt, B_pt)

tensor([[ 2, 17, 25],
        [ 8, 50, 61]])

In [28]:
# kalikan matrix A_tf dengan matrix B_tf
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 2, 17, 25],
       [ 8, 50, 61]], dtype=int32)>

SOAL 6

In [32]:
# buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?
np.dot(A, B)

#np.dot (B, A) tidak bisa dijalankan dikarenakan Error

array([[ 2, 17, 25],
       [ 8, 50, 61]])

In [33]:
np.dot (B, A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)