In [2]:
import torch

In [3]:
# lakukan perhitungan soal excercise menggunakan collab
#1
M_q = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
M_q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [4]:
V_q = torch.tensor([[-1, 1, -2]]).T
V_q

tensor([[-1],
        [ 1],
        [-2]])

In [6]:
torch.matmul(M_q, V_q)

tensor([[ -3],
        [ -9],
        [-15]])

In [10]:
# 2.
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [11]:
V_q = torch.tensor([[-1, 1, -2]]).T
V_q

tensor([[-1],
        [ 1],
        [-2]])

In [15]:
torch.matmul(I, V_q)

tensor([[-1],
        [ 1],
        [-2]])

In [16]:
#3.
M_q = torch.tensor([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
M_q

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [17]:
V_q = torch.tensor([[-1, 1, -2], [0, 1, 2]]).T
V_q

tensor([[-1,  0],
        [ 1,  1],
        [-2,  2]])

In [18]:
torch.matmul(M_q, V_q)

tensor([[ -3,   5],
        [ -9,  14],
        [-15,  23]])