In [1]:
import numpy as np

In [2]:
#1. buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris
x_sym = np.array([[2,5,1],[5,2,4],[1,4,7]])
x_sym


array([[2, 5, 1],
       [5, 2, 4],
       [1, 4, 7]])

In [4]:
x_sym.T

array([[2, 5, 1],
       [5, 2, 4],
       [1, 4, 7]])

In [5]:
import torch

In [6]:
#2.menggunakan pytorch, buatlah matriks identitas I dengan ukuran 4x4
I = torch.tensor([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [7]:
#menggunakan pytorch, buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor([[2],[2],[2],[2]])
b_pt


tensor([[2],
        [2],
        [2],
        [2]])

In [8]:
#kalikan matrix I dengan vector b_pt
torch.matmul(I,b_pt)

tensor([[2],
        [2],
        [2],
        [2]])