In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#buat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[-1, 8], [18, -81]])
X



array([[ -1,   8],
       [ 18, -81]])

In [4]:
#buat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[1.28571429, 0.12698413],
       [0.28571429, 0.01587302]])

In [5]:
#kalikan X dengan Xinv menggunakan numpy
np.dot(Xinv, X)

array([[ 1.0000000e+00, -4.4408921e-16],
       [ 0.0000000e+00,  1.0000000e+00]])





selesaikan persamaan berikut menggunakan numpy, tensorflow dan pytorch
$$ 4b + 2c = 4 $$
$$ -5b - 3c = -7 $$


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import torch
import tensorflow as tf


In [2]:
#Numpy
A = np.array([[4,2], [-5,-3]])
B = np.array([[4,-7]])
A
A_inv = np.linalg.inv(A)
C = A_inv.dot(B.T)
C

array([[-1.],
       [ 4.]])

In [3]:
#Pytorch
x = torch.tensor([[4.0, 2.0],[-5.0, -3.0]] )

y = torch.tensor([[4.0], [-7.0]])
x_inv = torch.linalg.inv(x)

solution = x_inv @ y

print(solution)

tensor([[-1.],
        [ 4.]])


In [4]:
#Pytorch
x = torch.tensor([[4.0, 2.0],[-5.0, -3.0]] )

y = torch.tensor([[4.0], [-7.0]])
x_inv = torch.linalg.inv(x)

solution = x_inv @ y

print(solution)

tensor([[-1.],
        [ 4.]])
