In [1]:
import numpy as np
import torch
import tensorflow as tf

In [2]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[18, 81], [8, 1], [1, 8]])
X

array([[18, 81],
       [ 8,  1],
       [ 1,  8]])

In [3]:
#buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[18, 81], [8, 1], [1, 8]])
X_pt

tensor([[18, 81],
        [ 8,  1],
        [ 1,  8]])

In [5]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[18, 81], [8, 1], [1, 8]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[18, 81],
       [ 8,  1],
       [ 1,  8]], dtype=int32)>

In [6]:
#lakukan perkalian matrix X, X_pt dengan suatu skalar
X_pt*2

tensor([[ 36, 162],
        [ 16,   2],
        [  2,  16]])

In [7]:
#lakukan perkalian matrix X, X_tf dengan suatu skalar
X_tf*2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 36, 162],
       [ 16,   2],
       [  2,  16]], dtype=int32)>

In [8]:
#akukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
X_pt+4

tensor([[22, 85],
        [12,  5],
        [ 5, 12]])

In [9]:
#akukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar
X_tf+4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[22, 85],
       [12,  5],
       [ 5, 12]], dtype=int32)>

In [10]:
#akukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
X_pt-6

tensor([[12, 75],
        [ 2, -5],
        [-5,  2]])

In [ ]:
#akukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar
X_tf-6

In [16]:
import numpy as np
import torch
import tensorflow as tf

In [13]:
#buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y =np.array([[2, 5], [25, 52], [5, 2]])
Y

array([[ 2,  5],
       [25, 52],
       [ 5,  2]])

In [14]:
#buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor([[2, 5], [25, 52], [5, 2]])
Y_pt

tensor([[ 2,  5],
        [25, 52],
        [ 5,  2]])

In [25]:
#buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[2, 5], [25, 52], [5, 2]])
Y_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[ 2,  5],
       [25, 52],
       [ 5,  2]], dtype=int32)>

In [20]:
#kalikan matrix X dengan Y
X*Y

array([[ 36, 405],
       [200,  52],
       [  5,  16]])

In [21]:
#kalikan matrix X_pt dengan Y_pt
X_pt*Y_pt

tensor([[ 36, 405],
        [200,  52],
        [  5,  16]])

In [26]:
#kalikan matrix X_tf dengan Y_tf
X_tf*Y_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[   4,   25],
       [ 625, 2704],
       [  25,    4]], dtype=int32)>