In [2]:
import numpy as np
import torch
import tensorflow as tf

In [3]:
#buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[25, 55, 61], [13, 1, 7]])
print("X=", X)

X= [[25 55 61]
 [13  1  7]]


In [4]:
#hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()
print("hasil penjumlahan elemen matrix X:", X.sum())

hasil penjumlahan elemen matrix X: 162


In [5]:
#buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[25, 55, 61], [13, 1, 7]])
print("X=", X_tf)

X= <tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 55, 61],
       [13,  1,  7]], dtype=int32)>


In [6]:
#buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[25, 55, 61], [13, 1, 7]])
print("X_pt=", X_pt)

X_pt= tensor([[25, 55, 61],
        [13,  1,  7]])


In [7]:
#hitung hasil penjumlahan seluruh elemen matrix X, X_pt, X_tf
sum_X = np.sum(X)
sum_X_pt = torch.sum(X_pt)
sum_X_tf = tf.reduce_sum(X_tf)

print(f"Sum All - NumPy: {sum_X}, PyTorch: {sum_X_pt.item()}, TF: {sum_X_tf.numpy()}")

Sum All - NumPy: 162, PyTorch: 162, TF: 162


In [8]:
#hitung hasil penjumlahan matrix X, X_pt, X_tf berdasarkan row nya
X.sum(axis=1)
print("hasil penjumlahan matrix X berdasarkan rownya:", X.sum(axis=1))
torch.sum(X_pt, 1)
print("hasil penjumlahan matrix X berdasarkan rownya:", torch.sum(X_pt, 1))
tf.reduce_sum(X_tf, axis=1)
print("hasil penjumlahan matrix X berdasarkan rownya:", tf.reduce_sum(X_tf, axis=1))

hasil penjumlahan matrix X berdasarkan rownya: [141  21]
hasil penjumlahan matrix X berdasarkan rownya: tensor([141,  21])
hasil penjumlahan matrix X berdasarkan rownya: tf.Tensor([141  21], shape=(2,), dtype=int32)


In [9]:
#hitung hasil penjumlahan matrix X, X_pt,X_tf berdasarkan kolom nya
X.sum(axis=0)
print("hasil penjumlahan matrix X berdasarkan rownya:", X.sum(axis=0))
torch.sum(X_pt, 0)
print("hasil penjumlahan matrix X berdasarkan rownya:", torch.sum(X_pt, 0))
tf.reduce_sum(X_tf, axis=0)
print("hasil penjumlahan matrix X berdasarkan rownya:", tf.reduce_sum(X_tf, axis=0))

hasil penjumlahan matrix X berdasarkan rownya: [38 56 68]
hasil penjumlahan matrix X berdasarkan rownya: tensor([38, 56, 68])
hasil penjumlahan matrix X berdasarkan rownya: tf.Tensor([38 56 68], shape=(3,), dtype=int32)


In [11]:
#hitung nilai minimal dari matrix X, X_pt dan X_tf
X.min()
print("nilai minimal dari matrix X adalah:", X.min())
print("nilai minimal dari matrix X adalah:", torch.min(X_pt))
print("nilai minimal dari matrix X adalah:", tf.reduce_min(X_tf))

nilai minimal dari matrix X adalah: 1
nilai minimal dari matrix X adalah: tensor(1)
nilai minimal dari matrix X adalah: tf.Tensor(1, shape=(), dtype=int32)


In [13]:
#hitung nilai maksimal dari matrix X, X_pt dan X_tf
X.max()
print("nilai maksimal dari matrix X adalah:", X.max())
torch.max(X_pt)
print("nilai maksimal dari matrix X adalah:", torch.max(X_pt))
tf.reduce_max(X_tf)
print("nilai maksimal dari matrix X adalah:", tf.reduce_max(X_tf))

nilai maksimal dari matrix X adalah: 61
nilai maksimal dari matrix X adalah: tensor(61)
nilai maksimal dari matrix X adalah: tf.Tensor(61, shape=(), dtype=int32)


In [14]:
#hitung nilai rata-rata dari matrix X, X_pt dan X_tf
np.mean(X)
print("nilai rata-rata dari matrix X adalah:", np.mean(X))
torch.mean(X_pt.float())
print("nilai rata-rata dari matrix X adalah:", torch.mean(X_pt.float()))
tf.reduce_mean(X_tf)
print("nilai rata-rata dari matrix X adalah:", tf.reduce_mean(X_tf))

nilai rata-rata dari matrix X adalah: 27.0
nilai rata-rata dari matrix X adalah: tensor(27.)
nilai rata-rata dari matrix X adalah: tf.Tensor(27, shape=(), dtype=int32)


In [15]:
#hitung hasil perkalian seluruh elemen matrix X
X.prod()
print("hasil perkalian seluruh elemen matrix X adalah:", X.prod())

hasil perkalian seluruh elemen matrix X adalah: 7632625


In [16]:
#hitung hasil perkalian seluruh elemen matrix X_pt
torch.prod(X_pt)
print("hasil perkalian seluruh elemen matrix X adalah:",torch.prod(X_pt))

hasil perkalian seluruh elemen matrix X adalah: tensor(7632625)


In [17]:
#hitung hasil perkalian seluruh elemen matrix X_tf
tf.reduce_prod(X_tf)
print("hasil perkalian seluruh elemen matrix X adalah:", tf.reduce_prod(X_tf))

hasil perkalian seluruh elemen matrix X adalah: tf.Tensor(7632625, shape=(), dtype=int32)
